name: min2
on:
  workflow_call:
    inputs:
      runner:
        type: string
        default: '["zap-proto-build-linux-amd64"]'
      mode:
        type: string
        default: buildx

permissions:
  contents: read
  packages: write

jobs:
  cicd:
    runs-on: ${{ fromJson(inputs.runner) }}
    steps:
      - uses: actions/checkout@v4
      - run: echo header-mechanics-ok
